markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: true
  auto_link: true
highlighter: rouge
theme: null
title: 好软分享
encoding: utf-8
markdown_ext:
"README.md"

include:
  - README.md

exclude:
  - LICENSE.txt
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Read
  - UpdateLog